//! 由 models.dev/api.json（2026-08-29 抓取）+ coding-plan-usage-apis.md 生成。
//! provider 模板种子数据：协议类型、付费模式按调研标注，
//! extra 为用量获取所需字段：cookie 类/OAuth 类/AK-SK 类，
//! 以及 usage（是否支持用量查询）与 usage_type（0=余额，1=月剩余额度/百分比）。
//! 规则：api.json 中无 base_url 的 provider 不收录；Command Code 为手动补充。

pub struct Template {
    pub name: &'static str,
    pub base_url: &'static str,
    pub protocol_type: i32,
    pub billing_mode: i32,
    pub extra: &'static str,
}

pub const TEMPLATES: &[Template] = &[
    Template {
        name: "302.AI",
        base_url: "https://api.302.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Abacus",
        base_url: "https://routellm.abacus.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "abliteration.ai",
        base_url: "https://api.abliteration.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AgentRouter",
        base_url: "https://agentrouter.org/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Agnes AI",
        base_url: "https://apihub.agnes-ai.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AI-ROUTER",
        base_url: "https://api.ai-router.dev/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "ai&",
        base_url: "https://api.aiand.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Aixy",
        base_url: "https://api.aixy-gateway.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AKI.IO",
        base_url: "https://aki.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Alibaba",
        base_url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"ak\": \"\", \"sk\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Alibaba (China)",
        base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"ak\": \"\", \"sk\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Alibaba Coding Plan",
        base_url: "https://coding-intl.dashscope.aliyuncs.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Alibaba Coding Plan (China)",
        base_url: "https://coding.dashscope.aliyuncs.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Alibaba Token Plan",
        base_url: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Alibaba Token Plan (China)",
        base_url: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Ambient",
        base_url: "https://api.ambient.xyz/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AMD",
        base_url: "https://developer.amd.com.cn/radeon/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AnyAPI",
        base_url: "https://api.anyapi.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Arcee",
        base_url: "https://api.arcee.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Atomic Chat",
        base_url: "http://127.0.0.1:1337/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Auriko",
        base_url: "https://api.auriko.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Bailing",
        base_url: "https://api.tbox.cn/api/llm/v1/chat/completions",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Baseten",
        base_url: "https://inference.baseten.co/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Berget.AI",
        base_url: "https://api.berget.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Blue Claw",
        base_url: "https://openai.blueclaw.network/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Chutes",
        base_url: "https://llm.chutes.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Clarifai",
        base_url: "https://api.clarifai.com/v2/ext/openai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Claudinio",
        base_url: "https://api.claudin.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "ClinePass",
        base_url: "https://api.cline.bot/api/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "CloudFerro Sherlock",
        base_url: "https://api-sherlock.cloudferro.com/openai/v1/",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Cloudflare Workers AI",
        base_url: "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Command Code",
        base_url: "https://api.commandcode.ai/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "CoralBricks",
        base_url: "https://inference.coralbricks.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Cortecs",
        base_url: "https://api.cortecs.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "CrofAI",
        base_url: "https://crof.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "CrossModel",
        base_url: "https://api.crossmodel.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Crusoe",
        base_url: "https://api.inference.crusoecloud.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "DaoXE",
        base_url: "https://daoxe.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Databricks",
        base_url: "https://${DATABRICKS_HOST}/ai-gateway/mlflow/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "DeepSeek",
        base_url: "https://api.deepseek.com",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "DigitalOcean",
        base_url: "https://inference.do-ai.run/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "DInference",
        base_url: "https://api.dinference.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "D.Run (China)",
        base_url: "https://chat.d.run/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "EBCloud",
        base_url: "https://maas-api.ebcloud.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Echo",
        base_url: "https://echo.tracerml.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Eden AI",
        base_url: "https://api.edenai.run/v3",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "EmpirioLabs AI",
        base_url: "https://api.empiriolabs.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "evroc",
        base_url: "https://models.think.evroc.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "FastRouter",
        base_url: "https://go.fastrouter.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Fireworks AI",
        base_url: "https://api.fireworks.ai/inference/v1/",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "FreeModel",
        base_url: "https://cc.freemodel.dev/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Friendli",
        base_url: "https://api.friendli.ai/serverless/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "FrogBot",
        base_url: "https://app.frogbot.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "GitHub Copilot",
        base_url: "https://api.githubcopilot.com",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"oauth_token\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "GMI Cloud",
        base_url: "https://api.gmi-serving.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "GreenPT",
        base_url: "https://api.greenpt.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Helicone",
        base_url: "https://ai-gateway.helicone.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Hetzner",
        base_url: "https://inference.hetzner.com/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "HPC-AI",
        base_url: "https://api.hpc-ai.com/inference/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Hugging Face",
        base_url: "https://router.huggingface.co/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Charm Hyper",
        base_url: "https://hyper.charm.land/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "iFlow",
        base_url: "https://apis.iflow.cn/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Impossibl",
        base_url: "https://api.impossibl.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Inception",
        base_url: "https://api.inceptionlabs.ai/v1/",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Inceptron",
        base_url: "https://api.inceptron.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Inference",
        base_url: "https://inference.net/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "InferX",
        base_url: "https://model.inferx.net/endpoints/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Infomaniak",
        base_url: "https://api.infomaniak.com/2/ai/${INFOMANIAK_PRODUCT_ID}/openai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "IO.NET",
        base_url: "https://api.intelligence.io.solutions/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "IteraCompute",
        base_url: "https://api.iteracompute.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Jalapeno Cloud",
        base_url: "https://api.jalapeno-cloud.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Jiekou.AI",
        base_url: "https://api.jiekou.ai/openai",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Kenari",
        base_url: "https://kenari.id/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Kilo Gateway",
        base_url: "https://api.kilo.ai/api/gateway",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Kimi For Coding",
        base_url: "https://api.kimi.com/coding/v1",
        protocol_type: 2,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Kosmik Compute",
        base_url: "https://api.koscompute.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "KUAE Cloud Coding Plan",
        base_url: "https://coding-plan-endpoint.kuaecloud.net/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "Lilac",
        base_url: "https://api.getlilac.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Llama",
        base_url: "https://api.llama.com/compat/v1/",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "DevPass (LLM Gateway)",
        base_url: "https://api.llmgateway.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LLM Gateway",
        base_url: "https://api.llmgateway.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LLM Tech",
        base_url: "https://api.llmtech.eu/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LLMTR",
        base_url: "https://llmtr.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LMStudio",
        base_url: "http://127.0.0.1:1234/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LongCat",
        base_url: "https://api.longcat.chat/openai",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LucidQuery",
        base_url: "https://api.lucidquery.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Lynkr",
        base_url: "http://127.0.0.1:8081/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Meganova",
        base_url: "https://api.meganova.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Merge Gateway",
        base_url: "https://api-gateway.merge.dev/v1/ai-sdk",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Meta",
        base_url: "https://api.meta.ai/v1",
        protocol_type: 1,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "MiniMax (minimax.io)",
        base_url: "https://api.minimax.io/anthropic/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "MiniMax (minimaxi.com)",
        base_url: "https://api.minimaxi.com/anthropic/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "MiniMax Token Plan (minimaxi.com)",
        base_url: "https://api.minimaxi.com/anthropic/v1",
        protocol_type: 2,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "MiniMax Token Plan (minimax.io)",
        base_url: "https://api.minimax.io/anthropic/v1",
        protocol_type: 2,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Mixlayer",
        base_url: "https://models.mixlayer.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Moark",
        base_url: "https://moark.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Modal",
        base_url: "https://inference.us-west.modal.direct/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Model Oracle AI",
        base_url: "https://api.modeloracle.com/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Modelis",
        base_url: "https://modelishub.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "ModelScope",
        base_url: "https://api-inference.modelscope.cn/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Moonshot AI",
        base_url: "https://api.moonshot.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Moonshot AI (China)",
        base_url: "https://api.moonshot.cn/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Morph",
        base_url: "https://api.morphllm.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "NanoGPT",
        base_url: "https://nano-gpt.com/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "NEAR AI Cloud",
        base_url: "https://cloud-api.near.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Nebius Token Factory",
        base_url: "https://api.tokenfactory.nebius.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Neon",
        base_url: "${NEON_AI_GATEWAY_BASE_URL}/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "NeoSmith",
        base_url: "https://router.neosmith.ai/v1",
        protocol_type: 1,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Neuralwatt",
        base_url: "https://api.neuralwatt.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Nova",
        base_url: "https://api.nova.amazon.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "NovitaAI",
        base_url: "https://api.novita.ai/openai",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Nvidia",
        base_url: "https://integrate.api.nvidia.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Ofox",
        base_url: "https://api.ofox.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Ollama Cloud",
        base_url: "https://ollama.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "OpenCode Zen",
        base_url: "https://opencode.ai/zen/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "OpenCode Go",
        base_url: "https://opencode.ai/zen/go/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "OpenReason",
        base_url: "https://api.openreason.app/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "OpenRouter",
        base_url: "https://openrouter.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Opper",
        base_url: "https://api.opper.ai/v3/compat",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "OrcaRouter",
        base_url: "https://api.orcarouter.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "OVHcloud AI Endpoints",
        base_url: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Pendra",
        base_url: "https://api.pendra.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Perplexity Agent",
        base_url: "https://api.perplexity.ai/v1",
        protocol_type: 1,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Pioneer",
        base_url: "https://api.pioneer.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Poe",
        base_url: "https://api.poe.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Poolside",
        base_url: "https://inference.poolside.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Privatemode AI",
        base_url: "http://localhost:8080/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "QiHang",
        base_url: "https://api.qhaigc.net/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Qiniu",
        base_url: "https://api.qnaigc.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Regolo AI",
        base_url: "https://api.regolo.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Requesty",
        base_url: "https://router.requesty.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "routing.run",
        base_url: "https://api.routing.run/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "RunInfra",
        base_url: "https://api.runinfra.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Sakana AI",
        base_url: "https://api.sakana.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Sarvam AI",
        base_url: "https://api.sarvam.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Scaleway",
        base_url: "https://api.scaleway.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "SCNet Token Plan",
        base_url: "https://api.scnet.cn/api/llm/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "SCX.ai",
        base_url: "https://api.scx.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "SiliconFlow",
        base_url: "https://api.siliconflow.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "SiliconFlow (China)",
        base_url: "https://api.siliconflow.cn/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Snowflake Cortex",
        base_url: "https://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/api/v2/cortex/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "STACKIT",
        base_url: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Standard Compute",
        base_url: "https://api.stdcmpt.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "StepFun (China)",
        base_url: "https://api.stepfun.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "StepFun (Global)",
        base_url: "https://api.stepfun.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "StepFun Step Plan (Global)",
        base_url: "https://api.stepfun.ai/step_plan/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "StepFun Step Plan (China)",
        base_url: "https://api.stepfun.com/step_plan/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Subconscious",
        base_url: "https://api.subconscious.dev/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "submodel",
        base_url: "https://llm.submodel.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Synthetic",
        base_url: "https://api.synthetic.new/openai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Tencent Coding Plan (China)",
        base_url: "https://api.lkeap.cloud.tencent.com/coding/v3",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "Tencent Token Plan",
        base_url: "https://api.lkeap.cloud.tencent.com/plan/v3",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "Tencent TokenHub",
        base_url: "https://tokenhub.tencentmaas.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "TensorX",
        base_url: "https://api.tensorx.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "The Grid AI",
        base_url: "https://api.thegrid.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Thinking Machines",
        base_url: "https://tinker.thinkingmachines.dev/services/tinker-prod/anthropic/api/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Tinfoil",
        base_url: "https://inference.tinfoil.sh/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "TokenGo",
        base_url: "https://api.tokengo.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "TrustedRouter",
        base_url: "https://api.trustedrouter.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Umans AI",
        base_url: "https://api.code.umans.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Umans AI Coding Plan",
        base_url: "https://api.code.umans.ai/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "UnoRouter",
        base_url: "https://api.unorouter.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Upstage",
        base_url: "https://api.upstage.ai/v1/solar",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Vancine",
        base_url: "https://vancine.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Vivgrid",
        base_url: "https://api.vivgrid.com/v1",
        protocol_type: 1,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Volcengine Ark",
        base_url: "https://ark.cn-beijing.volces.com/api/v3",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"ak\": \"\", \"sk\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Volcengine Ark Coding Plan",
        base_url: "https://ark.cn-beijing.volces.com/api/coding/v3",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"ak\": \"\", \"sk\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Vultr",
        base_url: "https://api.vultrinference.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Wafer",
        base_url: "https://pass.wafer.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Weights & Biases",
        base_url: "https://api.inference.wandb.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Xiaomi",
        base_url: "https://api.xiaomimimo.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Xiaomi Token Plan (Europe)",
        base_url: "https://token-plan-ams.xiaomimimo.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Xiaomi Token Plan (China)",
        base_url: "https://token-plan-cn.xiaomimimo.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Xiaomi Token Plan (Singapore)",
        base_url: "https://token-plan-sgp.xiaomimimo.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Xpersona",
        base_url: "https://www.xpersona.co/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Z.AI",
        base_url: "https://api.z.ai/api/paas/v4",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Z.AI Coding Plan",
        base_url: "https://api.z.ai/api/coding/paas/v4",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Zeldoc",
        base_url: "https://api.zeldoc.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Zenifra",
        base_url: "https://ai.zenifra.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "ZenMux",
        base_url: "https://zenmux.ai/api/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Zhipu AI",
        base_url: "https://open.bigmodel.cn/api/paas/v4",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Zhipu AI Coding Plan",
        base_url: "https://open.bigmodel.cn/api/coding/paas/v4",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
];
