use super::Template;

pub const TEMPLATES: &[Template] = &[
    Template {
        name: "FastRouter",
        base_url: "https://go.fastrouter.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Fireworks AI",
        base_url: "https://api.fireworks.ai/inference/v1/",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "FreeModel",
        base_url: "https://cc.freemodel.dev/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Friendli",
        base_url: "https://api.friendli.ai/serverless/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "FrogBot",
        base_url: "https://app.frogbot.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "GitHub Copilot",
        base_url: "https://api.githubcopilot.com",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"oauth_token\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "GMI Cloud",
        base_url: "https://api.gmi-serving.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "GreenPT",
        base_url: "https://api.greenpt.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Helicone",
        base_url: "https://ai-gateway.helicone.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Hetzner",
        base_url: "https://inference.hetzner.com/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "HPC-AI",
        base_url: "https://api.hpc-ai.com/inference/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Hugging Face",
        base_url: "https://router.huggingface.co/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Charm Hyper",
        base_url: "https://hyper.charm.land/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "iFlow",
        base_url: "https://apis.iflow.cn/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Impossibl",
        base_url: "https://api.impossibl.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Inception",
        base_url: "https://api.inceptionlabs.ai/v1/",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Inceptron",
        base_url: "https://api.inceptron.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Inference",
        base_url: "https://inference.net/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "InferX",
        base_url: "https://model.inferx.net/endpoints/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Infomaniak",
        base_url: "https://api.infomaniak.com/2/ai/${INFOMANIAK_PRODUCT_ID}/openai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "IO.NET",
        base_url: "https://api.intelligence.io.solutions/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "IteraCompute",
        base_url: "https://api.iteracompute.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Jalapeno Cloud",
        base_url: "https://api.jalapeno-cloud.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Jiekou.AI",
        base_url: "https://api.jiekou.ai/openai",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Kenari",
        base_url: "https://kenari.id/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Kilo Gateway",
        base_url: "https://api.kilo.ai/api/gateway",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Krill（按量付费）",
        base_url: "https://api-slb.krill-ai.net/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"email\": \"\", \"password\": \"\", \"jwt\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Krill（订阅制）",
        base_url: "https://api-slb.krill-ai.net/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"email\": \"\", \"password\": \"\", \"jwt\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Kimi For Coding",
        base_url: "https://api.kimi.com/coding/v1",
        protocol_type: 2,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Kosmik Compute",
        base_url: "https://api.koscompute.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "KUAE Cloud Coding Plan",
        base_url: "https://coding-plan-endpoint.kuaecloud.net/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "Lilac",
        base_url: "https://api.getlilac.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Llama",
        base_url: "https://api.llama.com/compat/v1/",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "DevPass (LLM Gateway)",
        base_url: "https://api.llmgateway.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LLM Gateway",
        base_url: "https://api.llmgateway.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LLM Tech",
        base_url: "https://api.llmtech.eu/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LLMTR",
        base_url: "https://llmtr.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LMStudio",
        base_url: "http://127.0.0.1:1234/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LongCat",
        base_url: "https://api.longcat.chat/openai",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "LucidQuery",
        base_url: "https://api.lucidquery.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Lynkr",
        base_url: "http://127.0.0.1:8081/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Meganova",
        base_url: "https://api.meganova.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Merge Gateway",
        base_url: "https://api-gateway.merge.dev/v1/ai-sdk",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Meta",
        base_url: "https://api.meta.ai/v1",
        protocol_type: 1,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "MiniMax (minimax.io)",
        base_url: "https://api.minimax.io/anthropic/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "MiniMax (minimaxi.com)",
        base_url: "https://api.minimaxi.com/anthropic/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "MiniMax Token Plan (minimaxi.com)",
        base_url: "https://api.minimaxi.com/anthropic/v1",
        protocol_type: 2,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "MiniMax Token Plan (minimax.io)",
        base_url: "https://api.minimax.io/anthropic/v1",
        protocol_type: 2,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
];
