use super::Template;

pub const TEMPLATES: &[Template] = &[
    Template {
        name: "STACKIT",
        base_url: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Standard Compute",
        base_url: "https://api.stdcmpt.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "StepFun (China)",
        base_url: "https://api.stepfun.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "StepFun (Global)",
        base_url: "https://api.stepfun.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "StepFun Step Plan (Global)",
        base_url: "https://api.stepfun.ai/step_plan/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "StepFun Step Plan (China)",
        base_url: "https://api.stepfun.com/step_plan/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Subconscious",
        base_url: "https://api.subconscious.dev/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "submodel",
        base_url: "https://llm.submodel.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Synthetic",
        base_url: "https://api.synthetic.new/openai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Tencent Coding Plan (China)",
        base_url: "https://api.lkeap.cloud.tencent.com/coding/v3",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "Tencent Token Plan",
        base_url: "https://api.lkeap.cloud.tencent.com/plan/v3",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "Tencent TokenHub",
        base_url: "https://tokenhub.tencentmaas.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "TensorX",
        base_url: "https://api.tensorx.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "The Grid AI",
        base_url: "https://api.thegrid.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Thinking Machines",
        base_url: "https://tinker.thinkingmachines.dev/services/tinker-prod/anthropic/api/v1",
        protocol_type: 2,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Tinfoil",
        base_url: "https://inference.tinfoil.sh/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "TokenGo",
        base_url: "https://api.tokengo.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "TokenRhythm",
        base_url: "https://tokenrhythm.studio/v1",
        protocol_type: 0,
        billing_mode: 0,
        // 用量查询：账号密码登录换取会话 Cookie（tokenrhythm.studio 钱包接口）。
        extra: "{\"account\": \"\", \"password\": \"\", \"tr_session\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "TokenRouter",
        base_url: "https://api.tokenrouter.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "TrustedRouter",
        base_url: "https://api.trustedrouter.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Umans AI",
        base_url: "https://api.code.umans.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Umans AI Coding Plan",
        base_url: "https://api.code.umans.ai/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "UnoRouter",
        base_url: "https://api.unorouter.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Upstage",
        base_url: "https://api.upstage.ai/v1/solar",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Vancine",
        base_url: "https://vancine.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Vivgrid",
        base_url: "https://api.vivgrid.com/v1",
        protocol_type: 1,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Volcengine Ark",
        base_url: "https://ark.cn-beijing.volces.com/api/v3",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"ak\": \"\", \"sk\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Volcengine Ark Coding Plan",
        base_url: "https://ark.cn-beijing.volces.com/api/coding/v3",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"ak\": \"\", \"sk\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Vultr",
        base_url: "https://api.vultrinference.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Wafer",
        base_url: "https://pass.wafer.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Weights & Biases",
        base_url: "https://api.inference.wandb.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Xiaomi",
        base_url: "https://api.xiaomimimo.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Xiaomi Token Plan (Europe)",
        base_url: "https://token-plan-ams.xiaomimimo.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Xiaomi Token Plan (China)",
        base_url: "https://token-plan-cn.xiaomimimo.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Xiaomi Token Plan (Singapore)",
        base_url: "https://token-plan-sgp.xiaomimimo.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Xpersona",
        base_url: "https://www.xpersona.co/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Z.AI",
        base_url: "https://api.z.ai/api/paas/v4",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Z.AI Coding Plan",
        base_url: "https://api.z.ai/api/coding/paas/v4",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Zeldoc",
        base_url: "https://api.zeldoc.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Zenifra",
        base_url: "https://ai.zenifra.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "ZenMux",
        base_url: "https://zenmux.ai/api/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Zhipu AI",
        base_url: "https://open.bigmodel.cn/api/paas/v4",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Zhipu AI Coding Plan",
        base_url: "https://open.bigmodel.cn/api/coding/paas/v4",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
];
