use super::Template;

pub const TEMPLATES: &[Template] = &[
    Template {
        name: "302.AI",
        base_url: "https://api.302.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Abacus",
        base_url: "https://routellm.abacus.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "abliteration.ai",
        base_url: "https://api.abliteration.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "above.dev",
        base_url: "https://api.above.dev/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AgentRouter",
        base_url: "https://agentrouter.org/v1",
        protocol_type: 0,
        billing_mode: 0,
        // 用量查询：CookieCloud 登录态（agentrouter.org）+ 用户手动填的 new_api_user（New-Api-User 头）。
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"new_api_user\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Agnes AI",
        base_url: "https://apihub.agnes-ai.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AI-ROUTER",
        base_url: "https://api.ai-router.dev/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "ai&",
        base_url: "https://api.aiand.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Aixy",
        base_url: "https://api.aixy-gateway.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AKI.IO",
        base_url: "https://aki.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Alibaba",
        base_url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"ak\": \"\", \"sk\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Alibaba (China)",
        base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"ak\": \"\", \"sk\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Alibaba Coding Plan",
        base_url: "https://coding-intl.dashscope.aliyuncs.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Alibaba Coding Plan (China)",
        base_url: "https://coding.dashscope.aliyuncs.com/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Alibaba Token Plan",
        base_url: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Alibaba Token Plan (China)",
        base_url: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "Ambient",
        base_url: "https://api.ambient.xyz/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AMD",
        base_url: "https://developer.amd.com.cn/radeon/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "AnyAPI",
        base_url: "https://api.anyapi.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Arcee",
        base_url: "https://api.arcee.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Atomic Chat",
        base_url: "http://127.0.0.1:1337/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Auriko",
        base_url: "https://api.auriko.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Bailing",
        base_url: "https://api.tbox.cn/api/llm/v1/chat/completions",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Baseten",
        base_url: "https://inference.baseten.co/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Berget.AI",
        base_url: "https://api.berget.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Bothub",
        base_url: "https://openai.bothub.ru/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Blue Claw",
        base_url: "https://openai.blueclaw.network/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Chutes",
        base_url: "https://llm.chutes.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Clarifai",
        base_url: "https://api.clarifai.com/v2/ext/openai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Claudinio",
        base_url: "https://api.claudin.io/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "ClinePass",
        base_url: "https://api.cline.bot/api/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "CloudFerro Sherlock",
        base_url: "https://api-sherlock.cloudferro.com/openai/v1/",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Cloudflare Workers AI",
        base_url: "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Command Code",
        base_url: "https://api.commandcode.ai/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "CoralBricks",
        base_url: "https://inference.coralbricks.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Cortecs",
        base_url: "https://api.cortecs.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "CrofAI",
        base_url: "https://crof.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "CrossModel",
        base_url: "https://api.crossmodel.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Crusoe",
        base_url: "https://api.inference.crusoecloud.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "DaoXE",
        base_url: "https://daoxe.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Databricks",
        base_url: "https://${DATABRICKS_HOST}/ai-gateway/mlflow/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "DeepSeek",
        base_url: "https://api.deepseek.com",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "DigitalOcean",
        base_url: "https://inference.do-ai.run/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "DInference",
        base_url: "https://api.dinference.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "D.Run (China)",
        base_url: "https://chat.d.run/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "EBCloud",
        base_url: "https://maas-api.ebcloud.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Echo",
        base_url: "https://echo.tracerml.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Eden AI",
        base_url: "https://api.edenai.run/v3",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "EmpirioLabs AI",
        base_url: "https://api.empiriolabs.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "evroc",
        base_url: "https://models.think.evroc.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
];
