use super::Template;

pub const TEMPLATES: &[Template] = &[
    Template {
        name: "Mixlayer",
        base_url: "https://models.mixlayer.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Moark",
        base_url: "https://moark.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Modal",
        base_url: "https://inference.us-west.modal.direct/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Model Oracle AI",
        base_url: "https://api.modeloracle.com/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Modelis",
        base_url: "https://modelishub.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "ModelScope",
        base_url: "https://api-inference.modelscope.cn/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Moonshot AI",
        base_url: "https://api.moonshot.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Moonshot AI (China)",
        base_url: "https://api.moonshot.cn/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Morph",
        base_url: "https://api.morphllm.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "NanoGPT",
        base_url: "https://nano-gpt.com/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "NEAR AI Cloud",
        base_url: "https://cloud-api.near.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Nebius Token Factory",
        base_url: "https://api.tokenfactory.nebius.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Neon",
        base_url: "${NEON_AI_GATEWAY_BASE_URL}/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "NeoSmith",
        base_url: "https://router.neosmith.ai/v1",
        protocol_type: 1,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Neuralwatt",
        base_url: "https://api.neuralwatt.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Nova",
        base_url: "https://api.nova.amazon.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "NovitaAI",
        base_url: "https://api.novita.ai/openai",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Nvidia",
        base_url: "https://integrate.api.nvidia.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Ofox",
        base_url: "https://api.ofox.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Ollama Cloud",
        base_url: "https://ollama.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "OpenCode Zen",
        base_url: "https://opencode.ai/zen/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "OpenCode Go",
        base_url: "https://opencode.ai/zen/go/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{\"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "OpenReason",
        base_url: "https://api.openreason.app/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "OpenRouter",
        base_url: "https://openrouter.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{\"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Opper",
        base_url: "https://api.opper.ai/v3/compat",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "OrcaRouter",
        base_url: "https://api.orcarouter.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "OVHcloud AI Endpoints",
        base_url: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Pendra",
        base_url: "https://api.pendra.ai/api/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Perplexity Agent",
        base_url: "https://api.perplexity.ai/v1",
        protocol_type: 1,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Pioneer",
        base_url: "https://api.pioneer.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Poe",
        base_url: "https://api.poe.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Poolside",
        base_url: "https://inference.poolside.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Privatemode AI",
        base_url: "http://localhost:8080/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "QiHang",
        base_url: "https://api.qhaigc.net/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Qiniu",
        base_url: "https://api.qnaigc.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Regolo AI",
        base_url: "https://api.regolo.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Requesty",
        base_url: "https://router.requesty.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "routing.run",
        base_url: "https://api.routing.run/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "RunInfra",
        base_url: "https://api.runinfra.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Sakana AI",
        base_url: "https://api.sakana.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Sarvam AI",
        base_url: "https://api.sarvam.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "Scaleway",
        base_url: "https://api.scaleway.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "SCNet Token Plan",
        base_url: "https://api.scnet.cn/api/llm/v1",
        protocol_type: 0,
        billing_mode: 1,
        extra: "{}",
    },
    Template {
        name: "SCX.ai",
        base_url: "https://api.scx.ai/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "SenseNova",
        base_url: "https://token.sensenova.cn/v1",
        protocol_type: 0,
        billing_mode: 1,
        // refresh_token 为后端派生的隐藏凭据（登录/续期后写回）；username/password 供失效自愈登录。
        extra: "{\"refresh_token\": \"\", \"username\": \"\", \"password\": \"\", \"usage\": true, \"usage_type\": 1}",
    },
    Template {
        name: "SiliconFlow",
        base_url: "https://api.siliconflow.com/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
    Template {
        name: "SiliconFlow (China)",
        base_url: "https://api.siliconflow.cn/v1",
        protocol_type: 0,
        billing_mode: 0,
        // 用量查询：CookieCloud 登录态（cloud.siliconflow.cn）+ 用户手动填的 x_subject_id。
        extra: "{\"cookie_cloud_server\": \"\", \"uuid\": \"\", \"password\": \"\", \"domain\": \"\", \"x_subject_id\": \"\", \"usage\": true, \"usage_type\": 0}",
    },
    Template {
        name: "Snowflake Cortex",
        base_url: "https://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/api/v2/cortex/v1",
        protocol_type: 0,
        billing_mode: 0,
        extra: "{}",
    },
];
